@host = {{$dotenv HOST}}
@token = {{$dotenv TOKEN}}

### Accept Request
PUT /users/@me/requests/1/accept
Host: {{host}}
Authorization: Bearer {{token}}

### Create Request
POST /users/@me/requests
Host: {{host}}
Authorization: Bearer {{token}}

recipient_id=2

### Delete Request
DELETE /users/@me/requests/1
Host: {{host}}
Authorization: Bearer {{token}}

### List Accepted
GET /users/@me/requests/accepted
Host: {{host}}
Authorization: Bearer {{token}}

### List Received
GET /users/@me/requests/received
Host: {{host}}
Authorization: Bearer {{token}}

### List Sent
GET /users/@me/requests/sent
Host: {{host}}
Authorization: Bearer {{token}}
