@host = {{$dotenv HOST}}
@token = {{$dotenv TOKEN}}

### Accept Request
PUT /users/@me/requests/1/accept
Authorization: Bearer {{token}}
Host: {{host}}

### Create Request
POST /users/@me/requests
Authorization: Bearer {{token}}
Host: {{host}}

recipient_id=2

### Delete Request
DELETE /users/@me/requests/1
Authorization: Bearer {{token}}
Host: {{host}}

### List Requests (accepted)
GET /users/@me/requests?status=accepted
Authorization: Bearer {{token}}
Host: {{host}}

### List Requests (received)
GET /users/@me/requests?status=received
Authorization: Bearer {{token}}
Host: {{host}}

### List Requests (sent)
GET /users/@me/requests?status=sent
Authorization: Bearer {{token}}
Host: {{host}}
