@host = {{$dotenv HOST}}
@token = {{$dotenv TOKEN}}

### Create Score (daily)
POST /users/@me/scores
Host: {{host}}
Authorization: Bearer {{token}}

date=2025-01-01&guesses=3&solution=crate&time=20000

### Create Score (practice)
POST /users/@me/scores
Host: {{host}}
Authorization: Bearer {{token}}

guesses=3&solution=crate&time=20000

### List Daily
GET /users/@me/scores/daily
Host: {{host}}
Authorization: Bearer {{token}}

### List Practice
GET /users/@me/scores/practice
Host: {{host}}
Authorization: Bearer {{token}}
