@host = {{$dotenv HOST}}
@token = {{$dotenv TOKEN}}

### Create Score (daily)
POST /users/@me/scores
Authorization: Bearer {{token}}
Host: {{host}}

date=2025-01-01&guesses=3&solution=crate&time=20000

### Create Score (practice)
POST /users/@me/scores
Authorization: Bearer {{token}}
Host: {{host}}

guesses=3&solution=crate&time=20000

### List Scores (daily)
GET /users/@me/scores?mode=daily
Authorization: Bearer {{token}}
Host: {{host}}

### List Scores (practice)
GET /users/@me/scores?mode=practice
Authorization: Bearer {{token}}
Host: {{host}}
