@host = {{$dotenv HOST}}
@token = {{$dotenv TOKEN}}

### Delete Session
DELETE /users/@me/sessions/1
Host: {{host}}
Authorization: Bearer {{token}}

### List Sessions
GET /users/@me/sessions
Host: {{host}}
Authorization: Bearer {{token}}
