@host = {{$dotenv HOST}}
@token = {{$dotenv TOKEN}}

### Delete Session
DELETE /users/@me/sessions/1
Authorization: Bearer {{token}}
Host: {{host}}

### List Sessions
GET /users/@me/sessions
Authorization: Bearer {{token}}
Host: {{host}}
