@host = {{$dotenv HOST}}
@token = {{$dotenv TOKEN}}

### Authorize User
POST /users/authorize
Host: {{host}}

username=jan&password=12345678

### Create User
POST /users
Host: {{host}}

username=jan&password=12345678

### Get Self
GET /users/@me
Host: {{host}}
Authorization: Bearer {{token}}

### Get User
GET /users/1
Host: {{host}}

### Search Users
GET /users?query=j
Host: {{host}}

### Update Self
PATCH /users/@me
Host: {{host}}
Authorization: Bearer {{token}}

username=updated&password=testtest
