@host = {{$dotenv HOST}}
@token = {{$dotenv TOKEN}}

### Authorize User
POST /users/authorize
Host: {{host}}

password=12345678&username=jan

### Create User
POST /users
Host: {{host}}

password=12345678&username=jan

### Get User
GET /users/1
Host: {{host}}

### Search Users
GET /users?query=j
Host: {{host}}

### Update User
PATCH /users/@me
Authorization: Bearer {{token}}
Host: {{host}}

password=testtest&username=updated
