@host = {{$dotenv HOST}}

### Get Daily (de)
GET /words/daily?language=de
Host: {{host}}

### Get Daily (en)
GET /words/daily?language=en
Host: {{host}}

### Get Words (de)
GET /words?language=de
Host: {{host}}

### Get Words (en)
GET /words?language=en
Host: {{host}}
