@root = http://localhost:3000

### Get Daily (de)
GET {{root}}/words/daily?language=de

### Get Daily (en)
GET {{root}}/words/daily?language=en

### Get Words (de)
GET {{root}}/words?language=de

### Get Words (en)
GET {{root}}/words?language=en
